ShareMe/Controllers/ArticleController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Xml;
using Microsoft.AspNetCore.Mvc;
using ShareMe.DAL.UnitOfWork;

namespace ShareMe.Controllers
{
    public class ArticleController : Controller
    {
        IUnitOfWork unitOfWork;

        public ArticleController(IUnitOfWork unitOfWork)
        {
            this.unitOfWork = unitOfWork;
        }

        public IActionResult Index(int? articleId, int? categoryId, int? authorId)
        {
            var articles = unitOfWork.ArticleRepository.Get(x =>
                (articleId == null || x.ArticleId == articleId) &&
                (categoryId == null || x.Category.CategoryId == categoryId) &&
                (authorId == null || x.Author.AuthorId == authorId)
                );
            return View(articles);
        }

        public IActionResult Details(int? articleId)
        {
            var article = unitOfWork.ArticleRepository.GetById(articleId);
            if (article == null)
            {
                return NotFound();
            }
            return View(article);
        }
    }
}

ShareMe/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ShareMe</title>
    @*<link rel="stylesheet" href="~/css/css_reset.css"/>*@
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header class="header">
        <div class="logo">
            <a asp-area="" asp-controller="Home" asp-action="Index">ShareMe</a>
        </div>
        <div class="main-menu">
            <ul>
                <li><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
                <li><a asp-area="" asp-controller="Article" asp-action="Index">Articles</a></li>
            </ul>
        </div>
        <div>
            <a asp-controller=Login asp-action="Index">Login</a>
        </div>
    </header>
    <div class="main">
        @RenderBody()
    </div>
    <footer class="footer">
        <div class="footer-content">
            &copy; 2019 - ShareMe
        </div>
    </footer>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>